In [4]:
import numpy as np
import matplotlib.pyplot as plt

#Intervall
a = 0.
b = 1.

#Schrittweite und Anzahl Schritte
h = 0.1
n = int((b-a)/h)

#Anzahl Zeilen im Vektor
rows = 4

x = np.zeros(n+1)
z = np.zeros([rows,n+1])

x[0] = a

#Startvektor
z[:,0] =np.array([0.,2.,0.,0.])

#Umgewandelte höhere Ordnung in 1. Ordnung
def f(x,z): 
    return np.array(
        [
            z[1],
            z[2], 
            z[3], 
            np.sin(x)+5-1.1*z[3]+0.1*z[2]+0.3*z[0]
        ])

#Hier das richtige auskommentieren!

#Euler
for i in range(0,n):
    x[i+1]=x[i]+h
    z[:,i+1]=z[:,i]+h*f(x[i],z[:,i])
    
    print(x[i+1])
    print(z[:,i+1])
    print()

#Mittelpunkt
# for i in range(0,n):
#     xh2 = x[i] + h / 2
#     yh2 = z[:,i] + h / 2 * f(x[i], z[:,i])

#     x[i+1]=x[i]+h
#     z[:,i+1]=z[:,i]+h*f(xh2, yh2)

#Modifiziert

#4-stufige Runge Kutta
# for i in range(0,n):
#     k1 = f(x[i], z[:,i])
#     k2 = f(x[i] + h/2, z[:,i] + h/2 * k1)
#     k3 = f(x[i] + h/2, z[:,i] + h/2 * k2)
#     k4 = f(x[i] + h, z[:,i] + h * k3)
#     x[i+1]=x[i]+h
#     z[:,i+1]=z[:,i]+h/6.*(k1 + 2*k2 + 2*k3 + k4)
    
#     print(x[i+1])
#     print(z[:,i+1])  

plt.plot(x,z[0,:],x,z[1,:],x,z[2,:],x,z[3,:]), plt.legend(["Lösung y(x)", "y'(x)","y''(x)","y'''(x)"])   

0.1
[0.2 2.  0.  0.5]

0.2
[0.4        2.         0.05       0.96098334]

0.30000000000000004
[0.6        2.005      0.14609833 1.38764211]

0.4
[0.8005     2.01960983 0.28486254 1.78401448]

0.5
[1.00246098 2.04809609 0.46326399 2.15357835]

0.6
[1.20727059 2.09442249 0.67862183 2.49933375]

0.7
[1.41671284 2.16228467 0.9285552  2.82387562]

0.7999999999999999
[1.63294131 2.25514019 1.21094276 3.12945801]

0.8999999999999999
[1.85845533 2.37623447 1.52388857 3.4180509 ]

0.9999999999999999
[2.09607877 2.52862332 1.86569366 3.69139054]



([<matplotlib.lines.Line2D at 0x13f4457d0>,
 <matplotlib.legend.Legend at 0x13f3caad0>)